#PBS -l nodes=1:ppn=1
#PBS -l mem=4gb
#PBS -l walltime=3:59:00
#PBS -j oe
#PBS -N len3
#PBS -l feature=intel14
#PBS -o /mnt/scratch/goldma72/length_${PBS_JOBID}.tmp

# Required by C++11
module load GNU/4.8.2

cd ${PBS_O_WORKDIR}

if [ ! -f length/finished.txt ]
then
  	qsub length.sub
    # Runs the correct job
    timeout -s SIGINT 14100 python length_scheduler.py ${PBS_JOBID}
    qstat -f ${PBS_JOBID}
fi
